[0m12:08:41.367944 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013C6DFC3C80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013C6DFC1430>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013C6DFC13A0>]}


============================== 12:08:41.371946 | 76c4de3a-22d0-40f7-a569-fc8cf69b50a2 ==============================
[0m12:08:41.371946 [info ] [MainThread]: Running with dbt=1.9.4
[0m12:08:41.371946 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\Study\\.dbt', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt init', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:08:59.745918 [debug] [MainThread]: Starter project path: C:\Users\Study\anaconda3\Lib\site-packages\dbt\include\starter_project
[0m12:08:59.763431 [info ] [MainThread]: 
Your new dbt project "dvd_rentals" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m12:08:59.764435 [info ] [MainThread]: Setting up your profile.
[0m12:09:08.141545 [debug] [MainThread]: Spark adapter: Setting pyhive.hive logging to ERROR
[0m12:09:08.141545 [debug] [MainThread]: Spark adapter: Setting thrift.transport logging to ERROR
[0m12:09:08.142547 [debug] [MainThread]: Spark adapter: Setting thrift.protocol logging to ERROR
[0m12:27:29.113764 [error] [MainThread]: Encountered an error:

[0m12:27:29.116276 [error] [MainThread]: Traceback (most recent call last):
  File "C:\Users\Study\anaconda3\Lib\site-packages\dbt\cli\requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Study\anaconda3\Lib\site-packages\dbt\cli\requires.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Study\anaconda3\Lib\site-packages\dbt\cli\main.py", line 477, in init
    results = task.run()
              ^^^^^^^^^^
  File "C:\Users\Study\anaconda3\Lib\site-packages\dbt\task\init.py", line 346, in run
    self.setup_profile(profile_name)
  File "C:\Users\Study\anaconda3\Lib\site-packages\dbt\task\init.py", line 262, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "C:\Users\Study\anaconda3\Lib\site-packages\dbt\task\init.py", line 179, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "C:\Users\Study\anaconda3\Lib\site-packages\dbt\task\init.py", line 163, in create_profile_from_profile_template
    target = self.generate_target_from_input(prompts, initial_target)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Study\anaconda3\Lib\site-packages\dbt\task\init.py", line 129, in generate_target_from_input
    target[key] = click.prompt(
                  ^^^^^^^^^^^^^
  File "C:\Users\Study\anaconda3\Lib\site-packages\click\termui.py", line 164, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Study\anaconda3\Lib\site-packages\click\termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m12:27:29.117279 [debug] [MainThread]: Command `dbt init` failed at 12:27:29.117279 after 1127.84 seconds
[0m12:27:29.118276 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013C6DA36180>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013C72F57D10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013C713EB6E0>]}
[0m12:27:29.118276 [debug] [MainThread]: Flushing usage events
[0m12:27:30.591390 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:36:07.018285 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021CA508C1A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021CA7BC7EF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021CA831DF40>]}


============================== 12:36:07.021285 | 863abf9b-98c9-428d-aac4-e67b2aa6fa65 ==============================
[0m12:36:07.021285 [info ] [MainThread]: Running with dbt=1.9.4
[0m12:36:07.021285 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Study\\.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m12:36:07.033799 [info ] [MainThread]: dbt version: 1.9.4
[0m12:36:07.034790 [info ] [MainThread]: python version: 3.12.7
[0m12:36:07.034790 [info ] [MainThread]: python path: C:\Users\Study\anaconda3\python.exe
[0m12:36:07.034790 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m12:36:07.043204 [debug] [MainThread]: Traceback (most recent call last):
  File "C:\Users\Study\anaconda3\Lib\site-packages\dbt\adapters\factory.py", line 68, in load_plugin
    mod: Any = import_module("." + name, "dbt.adapters")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Study\anaconda3\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Study\anaconda3\Lib\site-packages\dbt\adapters\snowflake\__init__.py", line 2, in <module>
    from dbt.adapters.snowflake.connections import SnowflakeConnectionManager  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Study\anaconda3\Lib\site-packages\dbt\adapters\snowflake\connections.py", line 14, in <module>
    import dbt.clients.agate_helper
ModuleNotFoundError: No module named 'dbt.clients.agate_helper'

[0m12:36:07.043204 [error] [MainThread]: Encountered an error:
No module named 'dbt.clients.agate_helper'
[0m12:36:07.045714 [error] [MainThread]: Traceback (most recent call last):
  File "C:\Users\Study\anaconda3\Lib\site-packages\dbt\cli\requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Study\anaconda3\Lib\site-packages\dbt\cli\requires.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Study\anaconda3\Lib\site-packages\dbt\cli\main.py", line 414, in debug
    results = task.run()
              ^^^^^^^^^^
  File "C:\Users\Study\anaconda3\Lib\site-packages\dbt\task\debug.py", line 114, in run
    load_profile_status: SubtaskStatus = self._load_profile()
                                         ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Study\anaconda3\Lib\site-packages\dbt\task\debug.py", line 205, in _load_profile
    profile: Profile = Profile.render(
                       ^^^^^^^^^^^^^^^
  File "C:\Users\Study\anaconda3\Lib\site-packages\dbt\config\profile.py", line 402, in render
    return cls.from_raw_profiles(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Study\anaconda3\Lib\site-packages\dbt\config\profile.py", line 368, in from_raw_profiles
    return cls.from_raw_profile_info(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Study\anaconda3\Lib\site-packages\dbt\config\profile.py", line 324, in from_raw_profile_info
    credentials: Credentials = cls._credentials_from_profile(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Study\anaconda3\Lib\site-packages\dbt\config\profile.py", line 148, in _credentials_from_profile
    cls = load_plugin(typename)
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Study\anaconda3\Lib\site-packages\dbt\adapters\factory.py", line 239, in load_plugin
    return FACTORY.load_plugin(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Study\anaconda3\Lib\site-packages\dbt\adapters\factory.py", line 68, in load_plugin
    mod: Any = import_module("." + name, "dbt.adapters")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Study\anaconda3\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Study\anaconda3\Lib\site-packages\dbt\adapters\snowflake\__init__.py", line 2, in <module>
    from dbt.adapters.snowflake.connections import SnowflakeConnectionManager  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Study\anaconda3\Lib\site-packages\dbt\adapters\snowflake\connections.py", line 14, in <module>
    import dbt.clients.agate_helper
ModuleNotFoundError: No module named 'dbt.clients.agate_helper'

[0m12:36:07.046718 [debug] [MainThread]: Command `dbt debug` failed at 12:36:07.046718 after 0.11 seconds
[0m12:36:07.047720 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021CA831DF40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021CA8A9DCA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021CA87DA8D0>]}
[0m12:36:07.047720 [debug] [MainThread]: Flushing usage events
[0m12:36:08.339359 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:37:03.155557 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000234E7F4A870>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000234E84F1AC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000234E84F25D0>]}


============================== 12:37:03.158562 | 7680122c-5aa9-4c48-9411-a2ddcfed4268 ==============================
[0m12:37:03.158562 [info ] [MainThread]: Running with dbt=1.9.4
[0m12:37:03.158562 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Study\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:37:03.171268 [info ] [MainThread]: dbt version: 1.9.4
[0m12:37:03.171268 [info ] [MainThread]: python version: 3.12.7
[0m12:37:03.172269 [info ] [MainThread]: python path: C:\Users\Study\anaconda3\python.exe
[0m12:37:03.172269 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m12:37:03.175775 [info ] [MainThread]: Error importing adapter: No module named 'dbt.adapters.snowflake'
[0m12:37:03.176779 [info ] [MainThread]: Using profiles dir at C:\Users\Study\.dbt
[0m12:37:03.176779 [info ] [MainThread]: Using profiles.yml file at C:\Users\Study\.dbt\profiles.yml
[0m12:37:03.176779 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\Study\Desktop\P2\DEC-P2\dbt_project.yml
[0m12:37:03.177782 [info ] [MainThread]: Configuration:
[0m12:37:03.177782 [info ] [MainThread]:   profiles.yml file [[31mERROR invalid[0m]
[0m12:37:03.177782 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m12:37:03.178780 [info ] [MainThread]: Required dependencies:
[0m12:37:03.178780 [debug] [MainThread]: Executing "git --help"
[0m12:37:03.200035 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone      Clone a repository into a new directory\n   init       Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add        Add file contents to the index\n   mv         Move or rename a file, a directory, or a symlink\n   restore    Restore working tree files\n   rm         Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect     Use binary search to find the commit that introduced a bug\n   diff       Show changes between commits, commit and working tree, etc\n   grep       Print lines matching a pattern\n   log        Show commit logs\n   show       Show various types of objects\n   status     Show the working tree status\n\ngrow, mark and tweak your common history\n   backfill   Download missing objects in a partial clone\n   branch     List, create, or delete branches\n   commit     Record changes to the repository\n   merge      Join two or more development histories together\n   rebase     Reapply commits on top of another base tip\n   reset      Reset current HEAD to the specified state\n   switch     Switch branches\n   tag        Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch      Download objects and refs from another repository\n   pull       Fetch from and integrate with another repository or a local branch\n   push       Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m12:37:03.200035 [debug] [MainThread]: STDERR: "b''"
[0m12:37:03.201031 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m12:37:03.201031 [info ] [MainThread]: Connection test skipped since no profile was found
[0m12:37:03.201031 [info ] [MainThread]: [31m2 checks failed:[0m
[0m12:37:03.201031 [info ] [MainThread]: Could not load dbt_project.yml
Profile loading failed for the following reason:
Runtime Error
  Credentials in profile "me", target "dev" invalid: Runtime Error
    Could not find adapter type snowflake!


[0m12:37:03.202031 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\Study\Desktop\P2\DEC-P2\dbt_project.yml> not found

[0m12:37:03.202031 [debug] [MainThread]: Command `dbt debug` failed at 12:37:03.202031 after 0.12 seconds
[0m12:37:03.203030 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000234E7F4A870>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000234EA636630>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000234EACC3D70>]}
[0m12:37:03.203030 [debug] [MainThread]: Flushing usage events
[0m12:37:04.346663 [debug] [MainThread]: An error was encountered while trying to flush usage events
